languageCode = "en-us"
ignoreFiles = [ "\\.files/README.md$",  ]
defaultContentLanguage = "en"
title = "Chatbot Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = ""
sectionPagesMenu = "main"
relativeURLs = true
publishDir = "docs"

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/kienpham2000/chatbot-workshop/edit/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "Kien Pham"
description = "Chatbot Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/kienpham2000/chatbot-workshop/"
branch = "master"
template_bucket = "chatbotworkshop.com"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "tango"
